#!/usr/bin/env python2

from xpybutil import conn, root
import xpybutil.event as event

# Do initial startup stuff
import pt3.state as state

# Bind keys
import pt3.keybind as keybind

import pt3.tile as tile

# Startup client management
import pt3.client as client

tile.update_tilers()
client.update_clients()

# Get those juices flowing...
state.PYTYLE_STATE = 'running'

# Start the event loop
event.event_loop(conn)

